#docker-compose.yml
version: '3.7'
services:
  mysql-master:
    image: "mysql"
    container_name: "mysql3307m"
    environment:
      MYSQL_ROOT_PASSWORD: root
    links:
      - mysql-slave
    ports:
      - "3307:3306"
    volumes:
      - ./master.cnf:/etc/mysql/my.cnf
      - ./mysql_files:/var/lib/mysql-files/
    hostname: mysql-master
  mysql-slave:
    image: "mysql"
    container_name: "mysql3308s"
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - ./slave.cnf:/etc/mysql/my.cnf
      - ./mysql_files:/var/lib/mysql-files/
    hostname: mysql-slave
